// src/components/App.vue
<template>
  <b-container>
    <b-card header="Github Feed Burner">
      <user-form @submit="setUsername"/>
      <b-tabs v-if="feeds.my && !loading">
        <b-tab title="My Feeds" active>
          <user-feeds :user="feeds.my"/>
        </b-tab>
        <b-tab title="Followers" v-if="feeds.followers.length > 0">
          <user-feeds v-for="follower in feeds.followers" :user="follower" :key="follower.username"/>
        </b-tab>
        <b-tab title="Following" v-if="feeds.following.length > 0">
          <user-feeds v-for="following in feeds.following" :user="following" :key="following.username"/>
        </b-tab>
      </b-tabs>
    </b-card>
  </b-container>
</template>

<script>
  import UserForm from './UserForm'
  import UserFeeds from './UserFeeds'
  import {mapActions, mapState} from 'vuex'

  export default {
    components: {UserForm, UserFeeds},
    name: 'app',
    computed: mapState(['username', 'loading', 'feeds']),
    methods: mapActions(['setUsername'])
  }
</script>

// src/components/App.svelte
<script>
  import { Card, Container, Tab, Tabs } from "svelte-chota";
  import createStore from "../store";
  import { onMount, setContext } from "svelte";
  import UserForm from "./UserForm.svelte";
  import UserFeeds from "./UserFeeds.svelte";

  const store = createStore();
  setContext("store", store);

  onMount(() => {
    store.restore();
  });

  let activeTab = "my";
</script>

<main>
  <Container>
    <Card>
      <UserForm />
      {#if $store.feeds.my && !$store.loading}
        <Tabs bind:active={activeTab} full>
          <Tab tabid="my">My Feeds</Tab>
          {#if $store.feeds.followers.length > 0}
            <Tab tabid="followers">Followers</Tab>
          {/if}
          {#if $store.feeds.following.length > 0}
            <Tab tabid="following">Following</Tab>
          {/if}
        </Tabs>
        {#if activeTab === "my"}
          <UserFeeds user={$store.feeds.my} />
        {/if}
        {#if activeTab === "followers"}
          {#each $store.feeds.followers as follower}
            <UserFeeds user={follower} />
          {/each}
        {/if}
        {#if activeTab === "following"}
          {#each $store.feeds.following as following}
            <UserFeeds user={following} />
          {/each}
        {/if}
      {/if}
    </Card>
  </Container>
</main>
