// src/components/UserForm.svelte
<script>
  import { getContext } from "svelte";
  import { Row, Input, Button } from "svelte-chota";

  const store = getContext("store");

  const onSubmit = e => {
    e.preventDefault();
    store.fetch();
  };
</script>

<Row>
  <Button on:click={() => store.login()} disabled={$store.token}>{$store.token ? "Logged In" : "Login"}</Button>
  <form on:submit={onSubmit}>
    <Input
      title="Username" type="text" placeholder="Username"
      disabled={$store.loading} autofocus value={$store.username}
      on:change={e => store.setUsername(e.target.value)} />
  </form>
</Row>

// src/components/UserForm.vue
<template>
  <b-form @submit.prevent="onSubmit">
    <b-form-input type="text" size="sm" v-model="username" placeholder="Username" :disabled="loading"
                  autofocus></b-form-input>
  </b-form>
</template>

<script>
  import {mapState} from 'vuex'

  export default {
    name: 'user-form',
    data() {
      return {username: ''}
    },
    computed: mapState(['loading']),
    mounted() {
      if (localStorage && (this.username = localStorage.getItem('username') || ''))
        this.$store.dispatch('setUsername', this.username)
    },
    methods: {
      onSubmit() {
        if (localStorage) localStorage.setItem('username', this.username)
        this.$store.dispatch('setUsername', this.username)
      }
    }
  }
</script>
